# Generated by Django 6.0.7 on 2026-07-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_category_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_body_images/', verbose_name="Matn ichidagi qo'shimcha rasm"),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Asosiy rasm (Orqa fon)'),
        ),
    ]
