# Generated by Django 6.0.7 on 2026-07-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_post_body_image_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='post_body_images/', verbose_name='Matn ichidagi 2-rasm'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_body_images/', verbose_name='Matn ichidagi 1-rasm'),
        ),
    ]
