# Generated by Django 6.0.7 on 2026-07-11 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_post_body_image_2_alter_post_body_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body_image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_image_2',
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post_gallery/', verbose_name='Rasm yuklash')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exam.post', verbose_name='Maqola')),
            ],
            options={
                'verbose_name': 'Maqola rasmi',
                'verbose_name_plural': 'Maqola rasmlari',
            },
        ),
    ]
